// Day 5 Feed Content Pack — Luxrear Business Club
// Centralized copy so wording changes don't require touching component logic.

export const FEED_WELCOME_MESSAGE = {
  title: "Welcome to your business feed.",
  body: "Discover opportunities, connect with members, learn from experts, and stay updated with the latest business activities.",
}

export const EMPTY_STATES = {
  noPosts: {
    title: "No Posts Yet",
    body: "No posts available at the moment. Be the first to share an opportunity with the community.",
  },
  noConnections: {
    title: "No Connections Yet",
    body: "Start connecting with members to build your business network.",
  },
  noOpportunitiesFound: {
    title: "No Opportunities Found",
    body: "Try adjusting your filters or check back later.",
  },
}

export const ENGAGEMENT_PROMPTS = [
  "Share an opportunity.",
  "Ask a business question.",
  "Introduce your business.",
  "Celebrate your achievements.",
  "Connect with other members.",
]

export const POST_SUCCESS_MESSAGES = {
  generic: "✅ Your post has been published successfully.",
  update: "✅ Your update has been shared.",
  opportunity: "✅ Your opportunity is now visible to members.",
  announcement: "✅ Your announcement has been posted.",
}

export const CONTENT_GUIDELINES = [
  "Share genuine opportunities.",
  "Respect other members.",
  "Provide accurate information.",
  "Avoid spam or misleading content.",
  "Support constructive discussions.",
]

export const COMMUNITY_MESSAGES = {
  welcome: "Welcome to the Luxrear community. Connect, collaborate, and grow your business.",
  engagement: "Share your ideas, ask questions, and contribute to meaningful discussions.",
  networking: "Strong businesses grow through strong relationships. Start connecting today.",
  support: "Our community thrives when members help one another succeed.",
}


// Sample/seed posts, shaped to match the real Post model + populated profile_id
// exactly, so swapping SAMPLE_POSTS for a real fetch() result requires no
// changes to PostCard or any consuming component.
//
// reaction_count and comment_count are real denormalized counters on the Post model
// comments live elsewhere (e.g. a separate endpoint) or aren't built yet.
export const SAMPLE_POSTS = [
  {
    _id: 'p1',
    type: 'OPPORTUNITY',
    title: 'Investment Opportunity',
    description: 'Seeking investors for a fast-growing agribusiness project focused on poultry production and food processing.\n\nLocation: Enugu, Nigeria\n\nInterested members can connect for further discussions.',
    location: 'Enugu, Nigeria',
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Adaeze Okonkwo', business_name: 'GreenHarvest Farms', profile_picture: null },
    created_at: '2026-06-25T09:30:00Z',
    reaction_count: 14,
    comment_count: 3,
  },
  {
    _id: 'p2',
    type: 'OPPORTUNITY',
    title: 'Partnership Request',
    description: 'Looking for logistics partners to support e-commerce deliveries across Southeast Nigeria.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Chidi Eze', business_name: 'SwiftCart Logistics', profile_picture: null },
    created_at: '2026-06-25T07:10:00Z',
    reaction_count: 6,
    comment_count: 1,
  },
  {
    _id: 'p3',
    type: 'OPPORTUNITY',
    title: 'Supplier Request',
    description: 'We need reliable packaging suppliers for our cosmetics business.\n\nPreferred location: Lagos or Abuja.',
    location: 'Lagos or Abuja',
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Funmi Adebayo', business_name: 'Lumière Cosmetics', profile_picture: null },
    created_at: '2026-06-24T16:45:00Z',
    reaction_count: 9,
    comment_count: 2,
  },
  {
    _id: 'p4',
    type: 'DEAL',
    title: 'Service Promotion',
    description: 'Our digital marketing agency helps businesses generate leads and increase sales through social media advertising.',
    location: null,
    image_url: null,
    is_featured: true,
    profile_id: { full_name: 'Tunde Bakare', business_name: 'Reach Digital', profile_picture: null },
    created_at: '2026-06-24T12:00:00Z',
    reaction_count: 21,
    comment_count: 5,
  },
  {
    _id: 'p5',
    type: 'OPPORTUNITY',
    title: 'Job Opportunity',
    description: 'We are hiring a graphic designer with experience in branding and digital content creation.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Ngozi Umeh', business_name: 'Studio Umeh', profile_picture: null },
    created_at: '2026-06-24T08:20:00Z',
    reaction_count: 11,
    comment_count: 4,
  },
  {
    _id: 'p6',
    type: 'UPDATE',
    title: 'Business Milestone',
    description: 'We are excited to announce the opening of our second business location.\n\nThank you to the Luxrear community for your support.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Emeka Nwosu', business_name: 'Nwosu Electronics', profile_picture: null },
    created_at: '2026-06-23T18:00:00Z',
    reaction_count: 38,
    comment_count: 9,
  },
  {
    _id: 'p7',
    type: 'UPDATE',
    title: 'Product Launch',
    description: 'Our new online learning platform is now available to entrepreneurs and small business owners.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Hauwa Yusuf', business_name: 'SkillBridge Africa', profile_picture: null },
    created_at: '2026-06-23T11:15:00Z',
    reaction_count: 17,
    comment_count: 2,
  },
  {
    _id: 'p8',
    type: 'UPDATE',
    title: 'Achievement Post',
    description: 'Proud to share that our company has successfully served over 1,000 customers this year.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Ifeoma Chukwu', business_name: 'Chukwu & Co.', profile_picture: null },
    created_at: '2026-06-22T14:30:00Z',
    reaction_count: 26,
    comment_count: 6,
  },
  {
    _id: 'p9',
    type: 'LEARNING',
    title: 'Business Tip',
    description: 'Customer trust is one of the strongest assets any business can build. Deliver quality consistently.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Luxrear Team', business_name: 'Luxrear Business Club', profile_picture: null },
    created_at: '2026-06-22T09:00:00Z',
    reaction_count: 42,
    comment_count: 3,
  },
  {
    _id: 'p10',
    type: 'LEARNING',
    title: 'Financial Advice',
    description: 'Separate personal finances from business finances to improve financial management.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Luxrear Team', business_name: 'Luxrear Business Club', profile_picture: null },
    created_at: '2026-06-21T09:00:00Z',
    reaction_count: 33,
    comment_count: 2,
  },
  {
    _id: 'p11',
    type: 'LEARNING',
    title: 'Marketing Insight',
    description: 'Focus on solving customer problems instead of simply promoting products.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Luxrear Team', business_name: 'Luxrear Business Club', profile_picture: null },
    created_at: '2026-06-20T09:00:00Z',
    reaction_count: 29,
    comment_count: 1,
  },
  {
    _id: 'p12',
    type: 'ANNOUNCEMENT',
    title: 'Community Announcement',
    description: 'Welcome our newest members to the Luxrear Business Club community.',
    location: null,
    image_url: null,
    is_featured: true,
    profile_id: { full_name: 'Luxrear Team', business_name: 'Luxrear Business Club', profile_picture: null },
    created_at: '2026-06-26T08:00:00Z',
    reaction_count: 19,
    comment_count: 4,
  },
  {
    _id: 'p13',
    type: 'ANNOUNCEMENT',
    title: 'Weekly Announcement',
    description: 'New opportunities have been posted this week. Explore the feed and connect with members.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Luxrear Team', business_name: 'Luxrear Business Club', profile_picture: null },
    created_at: '2026-06-25T08:00:00Z',
    reaction_count: 8,
    comment_count: 0,
  },
  {
    _id: 'p14',
    type: 'ANNOUNCEMENT',
    title: 'Event Announcement',
    description: 'Join our upcoming business networking session this Friday.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Luxrear Team', business_name: 'Luxrear Business Club', profile_picture: null },
    created_at: '2026-06-24T08:00:00Z',
    reaction_count: 24,
    comment_count: 7,
  },
  {
    _id: 'p15',
    type: 'ANNOUNCEMENT',
    title: 'System Announcement',
    description: 'New features have been added to improve your networking experience.',
    location: null,
    image_url: null,
    is_featured: false,
    profile_id: { full_name: 'Luxrear Team', business_name: 'Luxrear Business Club', profile_picture: null },
    created_at: '2026-06-19T08:00:00Z',
    reaction_count: 15,
    comment_count: 1,
  },
]